{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "grafana1.serviceAccountName" . }}
  labels:
{{ include "grafana1.labels" . | indent 4 }}
{{- end -}}
